export const NODES = [
  {
    id: 'start-node',
    type: 'start-node',
    x: 200,
    y: 200,
    properties: {
      node_icon_name: 'node-start',
      node_name: '开始节点',
      node_type: '1',
      node_sub_type: '0',
      field_key: '',
      effective_time: [],
      target_user: 1,
    },
  },
  {
    id: 'hi',
    type: 'message-node',
    x: 200,
    y: 600,
    properties: {
      node_icon_name: 'node-hi',
      node_name: '欢迎语',
      node_type: '2',
      node_sub_type: '21',
      field_key: 'hi',
      message_list: [
        {
          delay: 20,
          msg_type: 'menu',
          content: '墙面翻新/修补/翻新等全国连锁，服务3千万+家庭，真实质保1-5年，可全国施工',
          question: [{ content: '免费上门检测？' }, { content: '免费提供详细施工方案及报价' }],
        },
        {
          delay: 10,
          msg_type: 'menu',
          content: '您好，你是想要了解墙面翻新吗？',
          question: [{ content: '您是想了解墙面翻新吗' }],
        },
      ],
    },
  },
  {
    id: 'a1',
    type: 'message-node',
    x: 600,
    y: 400,
    properties: {
      node_icon_name: 'node-message',
      node_name: '发送消息',
      node_type: '2',
      node_sub_type: '21',
      field_key: '',
      message_list: [
        {
          delay: 3,
          msg_type: 'menu',
          content: '您好，你是想要了解墙面翻新吗？',
          question: [
            { content: '是的没错' },
            { content: '是的没错' },
            { content: '是的没错' },
            { content: '是的没错' },
            { content: '是的没错' },
          ],
        },
        {
          delay: 3,
          msg_type: 'image',
          content:
            'https://xkf-upload-oss.xiaokefu.com.cn/t/chat_img_b/800078833/359251/202412/2e/a0d64a29b8f8a55aa609dd4e1849b4.png?x-oss-process=image/resize,l_1000',
          question: [],
        },
        {
          delay: 3,
          msg_type: 'text',
          content: '您好，你是想要了解墙面翻新吗？',
          question: [],
        },
      ],
    },
  },
  {
    id: 'b1',
    type: 'question-node',
    x: 1000,
    y: 100,
    properties: {
      node_icon_name: 'node-phone',
      node_name: '问手机号',
      node_type: '3',
      node_sub_type: '31',
      field_key: 'mobile',
      delay_question: 5,
      question_reference: [
        '您好，可以留下您的手机号吗？稍后会有专属客户经理联系您跟您预约上门时间',
      ],
    },
  },
  {
    id: 'b2',
    type: 'question-node',
    x: 1000,
    y: 300,
    properties: {
      node_icon_name: 'node-name',
      node_name: '问姓名',
      node_type: '3',
      node_sub_type: '31',
      field_key: 'name',
      delay_question: 5,
      question_reference: ['好的，该怎么称呼您呢？'],
    },
  },
  {
    id: 'b3',
    type: 'question-node',
    x: 1000,
    y: 500,
    properties: {
      node_icon_name: 'node-wechat',
      node_name: '问微信号',
      node_type: '3',
      node_sub_type: '31',
      field_key: 'weixin',
      delay_question: 5,
      question_reference: ['您好，请问您微信多少？'],
    },
  },
  {
    id: 'b4',
    type: 'question-node',
    x: 1000,
    y: 700,
    properties: {
      node_icon_name: 'node-city',
      node_name: '问城市',
      node_type: '3',
      node_sub_type: '31',
      field_key: 'city',
      delay_question: 5,
      question_reference: ['您好，请问您在哪个城市呢？'],
    },
  },
  {
    id: 'b5',
    type: 'question-node',
    x: 1000,
    y: 900,
    properties: {
      node_icon_name: 'node-custom',
      node_name: '自定义字段',
      node_type: '3',
      node_sub_type: '32',
      field_key: 'custom',
      delay_question: 5,
      question_reference: ['您好，自定义字段问题？'],
    },
  },
  {
    id: 'c1',
    type: 'action-node',
    x: 1400,
    y: 100,
    properties: {
      node_icon_name: 'node-notice',
      node_name: '发送通知',
      node_type: '4',
      node_sub_type: '41',
      field_key: '',
      notice_content: '',
      content: '发送企微群消息通知',
    },
  },
  {
    id: 'c2',
    type: 'action-node',
    x: 1400,
    y: 300,
    properties: {
      node_icon_name: 'node-close',
      node_name: '结束对话',
      node_type: '5',
      node_sub_type: '51',
      field_key: '',
      content: '触发时自动结束对话。访客之后再咨询会重新从开始节点继续执行。',
    },
  },
  {
    id: 'c3',
    type: 'action-node',
    x: 1400,
    y: 500,
    properties: {
      node_icon_name: 'node-service',
      node_name: '转人工',
      node_type: '5',
      node_sub_type: '52',
      field_key: '',
      switch_content: '',
      content: '自动分配客服',
    },
  },
]
