#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import re
import shutil
import sys
import tempfile
import zipfile
from pathlib import Path
from typing import Any


if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")
if hasattr(sys.stderr, "reconfigure"):
    sys.stderr.reconfigure(encoding="utf-8")


SKILL_NAME_RE = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")
REQUIRED_METADATA_FIELDS = ("name", "title", "description", "source_summary", "topic_groups")
CRAWL_COVERAGE_FIELDS = (
    "requested",
    "attempted",
    "succeeded",
    "failed",
    "max_consecutive_timeouts",
    "skipped_pages_after_timeout_stop",
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Build a reusable skill zip from a JSONL web index and model-provided metadata.")
    parser.add_argument("--index", required=True, help="JSONL index generated by crawl_urls.py.")
    parser.add_argument("--metadata", required=True, help="UTF-8 JSON file containing model-provided skill metadata and source profile.")
    parser.add_argument("--zip-out", required=True, help="Destination zip path.")
    return parser.parse_args()


def require_text(value: Any, label: str, *, max_length: int) -> str:
    if not isinstance(value, str):
        raise ValueError(f"{label} must be a string")
    text = " ".join(value.split()).strip()
    if not text:
        raise ValueError(f"{label} must not be empty")
    if len(text) > max_length:
        raise ValueError(f"{label} must not exceed {max_length} characters")
    return text


def optional_text_list(value: Any, label: str, *, max_items: int, max_length: int) -> list[str]:
    if value is None:
        return []
    if not isinstance(value, list) or len(value) > max_items:
        raise ValueError(f"{label} must be an array with at most {max_items} items")
    result: list[str] = []
    seen: set[str] = set()
    for index, item in enumerate(value):
        text = require_text(item, f"{label}[{index}]", max_length=max_length)
        key = text.casefold()
        if key not in seen:
            seen.add(key)
            result.append(text)
    return result


def load_index(path: Path) -> list[dict[str, Any]]:
    pages: list[dict[str, Any]] = []
    seen_urls: set[str] = set()
    for line_number, raw_line in enumerate(path.read_text(encoding="utf-8-sig").splitlines(), start=1):
        if not raw_line.strip():
            continue
        try:
            page = json.loads(raw_line)
        except json.JSONDecodeError as exc:
            raise ValueError(f"invalid JSONL at {path}:{line_number}: {exc}") from exc
        if not isinstance(page, dict):
            raise ValueError(f"index record at {path}:{line_number} must be an object")
        for field in ("url", "title", "description", "keywords", "html_path"):
            if field not in page:
                raise ValueError(f"index record at {path}:{line_number} is missing {field}")
        url = str(page["url"]).strip()
        if not url or url in seen_urls:
            raise ValueError(f"index contains an empty or duplicate URL at {path}:{line_number}: {url}")
        if not isinstance(page["keywords"], list):
            raise ValueError(f"index record keywords at {path}:{line_number} must be an array")
        seen_urls.add(url)
        pages.append(page)
    if not pages:
        raise ValueError(f"index has no page records: {path}")
    return pages


def load_metadata(path: Path, page_urls: set[str]) -> dict[str, Any]:
    try:
        raw = json.loads(path.read_text(encoding="utf-8-sig"))
    except json.JSONDecodeError as exc:
        raise ValueError(f"invalid metadata JSON at {path}: {exc}") from exc
    if not isinstance(raw, dict):
        raise ValueError("metadata root must be an object")
    missing = [field for field in REQUIRED_METADATA_FIELDS if field not in raw]
    if missing:
        raise ValueError(f"metadata is missing required fields: {', '.join(missing)}")

    name = require_text(raw["name"], "metadata.name", max_length=50)
    if not SKILL_NAME_RE.fullmatch(name):
        raise ValueError("metadata.name must use lowercase letters, digits, and single hyphens only")
    title = require_text(raw["title"], "metadata.title", max_length=80)
    description = require_text(raw["description"], "metadata.description", max_length=500)
    source_summary = require_text(raw["source_summary"], "metadata.source_summary", max_length=1200)

    groups = raw["topic_groups"]
    if not isinstance(groups, list) or not 1 <= len(groups) <= 12:
        raise ValueError("metadata.topic_groups must contain 1-12 items")
    topic_groups: list[dict[str, Any]] = []
    for index, item in enumerate(groups):
        label = f"metadata.topic_groups[{index}]"
        if not isinstance(item, dict):
            raise ValueError(f"{label} must be an object")
        page_group_urls = optional_text_list(item.get("page_urls"), f"{label}.page_urls", max_items=3, max_length=2048)
        unknown_urls = [url for url in page_group_urls if url not in page_urls]
        if unknown_urls:
            raise ValueError(f"{label}.page_urls contains URLs that are not present in the index: {unknown_urls[0]}")
        topic_groups.append(
            {
                "name": require_text(item.get("name"), f"{label}.name", max_length=80),
                "summary": require_text(item.get("summary"), f"{label}.summary", max_length=300),
                "query_terms": optional_text_list(item.get("query_terms"), f"{label}.query_terms", max_items=10, max_length=80),
                "page_urls": page_group_urls,
            }
        )

    aliases_raw = raw.get("aliases", [])
    if not isinstance(aliases_raw, list) or len(aliases_raw) > 20:
        raise ValueError("metadata.aliases must be an array with at most 20 items")
    aliases: list[dict[str, Any]] = []
    for index, item in enumerate(aliases_raw):
        label = f"metadata.aliases[{index}]"
        if not isinstance(item, dict):
            raise ValueError(f"{label} must be an object")
        aliases.append(
            {
                "canonical": require_text(item.get("canonical"), f"{label}.canonical", max_length=80),
                "aliases": optional_text_list(item.get("aliases"), f"{label}.aliases", max_items=10, max_length=80),
            }
        )

    return {
        "name": name,
        "title": title,
        "description": description,
        "source_summary": source_summary,
        "topic_groups": topic_groups,
        "aliases": aliases,
        "coverage_notes": optional_text_list(raw.get("coverage_notes"), "metadata.coverage_notes", max_items=10, max_length=300),
    }


def load_crawl_coverage(path: Path, page_count: int) -> dict[str, int | bool]:
    if not path.is_file():
        raise ValueError(f"crawl log not found: {path}")
    run_done = ""
    for line in path.read_text(encoding="utf-8-sig").splitlines():
        if "[crawl_urls]" in line and " run.done " in f" {line} ":
            run_done = line
    if not run_done:
        raise ValueError(f"crawl log has no crawl_urls run.done event: {path}")

    coverage: dict[str, int | bool] = {}
    for field in CRAWL_COVERAGE_FIELDS:
        match = re.search(rf"(?:^|\s){re.escape(field)}=(-?\d+)(?:\s|$)", run_done)
        if not match:
            raise ValueError(f"crawl run.done is missing {field}: {path}")
        coverage[field] = int(match.group(1))
    duplicate_match = re.search(r"(?:^|\s)duplicate_final_urls=(-?\d+)(?:\s|$)", run_done)
    coverage["duplicate_final_urls"] = int(duplicate_match.group(1)) if duplicate_match else 0
    stopped_match = re.search(r"(?:^|\s)stopped_by_consecutive_timeouts=(true|false)(?:\s|$)", run_done)
    if not stopped_match:
        raise ValueError(f"crawl run.done is missing stopped_by_consecutive_timeouts: {path}")
    coverage["stopped_by_consecutive_timeouts"] = stopped_match.group(1) == "true"

    requested = int(coverage["requested"])
    attempted = int(coverage["attempted"])
    succeeded = int(coverage["succeeded"])
    failed = int(coverage["failed"])
    duplicate_final_urls = int(coverage["duplicate_final_urls"])
    skipped = int(coverage["skipped_pages_after_timeout_stop"])
    if (
        requested <= 0
        or attempted < 0
        or succeeded < 0
        or failed < 0
        or duplicate_final_urls < 0
        or skipped < 0
    ):
        raise ValueError(f"crawl run.done has invalid negative or empty counts: {path}")
    if attempted + skipped != requested:
        raise ValueError("crawl coverage mismatch: attempted plus skipped must equal requested")
    if succeeded + failed + duplicate_final_urls != attempted:
        raise ValueError(
            "crawl coverage mismatch: succeeded plus failed plus duplicate final URLs must equal attempted"
        )
    if succeeded != page_count:
        raise ValueError("crawl coverage mismatch: succeeded must equal the number of index records")
    return coverage


def yaml_quote(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def markdown_text(value: str) -> str:
    return value.replace("\r", " ").replace("\n", " ").strip()


def crawl_coverage_note(coverage: dict[str, int | bool]) -> str:
    requested = int(coverage["requested"])
    succeeded = int(coverage["succeeded"])
    failed = int(coverage["failed"])
    duplicate_final_urls = int(coverage["duplicate_final_urls"])
    skipped = int(coverage["skipped_pages_after_timeout_stop"])
    if failed == 0 and skipped == 0 and duplicate_final_urls == 0:
        if requested == 1:
            return "The prepared page was captured successfully."
        return f"All {requested} prepared pages were captured successfully."
    duplicate_note = (
        f" {duplicate_final_urls} prepared URL"
        f"{' redirected' if duplicate_final_urls == 1 else 's redirected'}"
        " to already captured pages."
        if duplicate_final_urls
        else ""
    )
    if failed == 0 and skipped == 0:
        return (
            f"Captured {succeeded} unique pages from {requested} prepared URLs."
            f"{duplicate_note}"
        )
    reason = " The crawl stopped after consecutive timeouts." if coverage["stopped_by_consecutive_timeouts"] else ""
    requested_label = "page" if requested == 1 else "pages"
    failed_label = "page" if failed == 1 else "pages"
    skipped_label = "page was" if skipped == 1 else "pages were"
    return (
        f"Crawl coverage is partial: captured {succeeded} of {requested} prepared {requested_label}; "
        f"{failed} attempted {failed_label} failed and {skipped} {skipped_label} skipped."
        f"{duplicate_note}{reason}"
    )


def profile_markdown(metadata: dict[str, Any], coverage: dict[str, int | bool]) -> str:
    lines = ["## Source profile", "", markdown_text(metadata["source_summary"]), "", "### Topic guide", ""]
    for group in metadata["topic_groups"]:
        lines.extend([f"- **{markdown_text(group['name'])}**: {markdown_text(group['summary'])}"])
        if group["query_terms"]:
            lines.append(f"  - Query terms: {', '.join(f'`{term}`' for term in group['query_terms'])}")
        if group["page_urls"]:
            lines.append(f"  - Representative pages: {', '.join(f'`{url}`' for url in group['page_urls'])}")
    if metadata["aliases"]:
        lines.extend(["", "### Terminology aliases", ""])
        for item in metadata["aliases"]:
            lines.append(f"- `{item['canonical']}`: {', '.join(f'`{alias}`' for alias in item['aliases'])}")
    lines.extend(["", "### Coverage boundaries", ""])
    if metadata["coverage_notes"]:
        lines.extend(f"- {markdown_text(note)}" for note in metadata["coverage_notes"])
    lines.append(f"- {crawl_coverage_note(coverage)}")
    return "\n".join(lines)


def build_skill_markdown(metadata: dict[str, Any], coverage: dict[str, int | bool]) -> str:
    return f"""---
name: {metadata['name']}
description: {yaml_quote(metadata['description'])}
---

# {metadata['title']}

{profile_markdown(metadata, coverage)}

## Retrieval workflow

1. Use the source profile and terminology aliases to choose two to four discriminating query terms from the user's question.
   Separate multiple query terms with a literal `|`, for example `product|feature|error`; do not use spaces as the
   separator.
2. Search the bounded JSONL index and return no more than three candidate pages. When searching the bundled skill
   content, do not pass `--index`; the script locates `references/web-index.jsonl` from its own location:

```bash
python3 scripts/search_index.py --query "product|feature|error" --limit 3
```

3. Inspect only the returned candidate files. For each file, run at most one targeted search with bounded matches and context:

```bash
rg -n -i -m 12 -C 3 "feature|parameter" <candidate-html-path>
```

4. Read one small nearby range only when the search context is insufficient. Never read a large HTML file in full and never enumerate all files under `references/html/`.
5. Adjust the index query at most once. Stop when the second query still has no useful evidence.
6. Use no more than three candidate pages and stop as soon as the evidence is sufficient.
7. Fetch one live page only when the saved snapshots are insufficient or the user explicitly requests current information:

```bash
python3 scripts/fetch_rendered_html.py "https://example.com/docs/page"
```

Use the rendered HTML printed by that command directly. State whether the answer uses saved snapshots or a live fetch, and include the source URLs.

## Bundled resources

- `references/web-index.jsonl` is the only page index. Each line contains `url`, `title`, `description`, `keywords`, and `html_path`.
- `references/html/` contains script-stripped rendered HTML snapshots.
- `scripts/search_index.py` performs deterministic bounded retrieval over the index.
- `scripts/fetch_rendered_html.py` fetches the latest rendered HTML for one public URL and applies the same body selectors used during indexing.
"""


def bounded_short_description(description: str) -> str:
    compact = " ".join(description.split())
    if len(compact) < 25:
        compact = f"Use indexed rendered web pages. {compact}".strip()
    return compact[:64].rstrip()


def build_openai_yaml(metadata: dict[str, Any]) -> str:
    prompt = f"Use ${metadata['name']} to search the bounded web index before answering from the saved rendered pages."
    return (
        "interface:\n"
        f"  display_name: {yaml_quote(metadata['title'])}\n"
        f"  short_description: {yaml_quote(bounded_short_description(metadata['description']))}\n"
        f"  default_prompt: {yaml_quote(prompt)}\n"
    )


def resolve_html_path(index_path: Path, stored_path: str) -> Path:
    candidate = Path(stored_path)
    if candidate.is_absolute():
        raise ValueError(f"HTML snapshot path must be relative to the index: {stored_path}")
    index_dir = index_path.parent.resolve()
    candidate = (index_dir / candidate).resolve()
    try:
        candidate.relative_to(index_dir)
    except ValueError as exc:
        raise ValueError(f"HTML snapshot path escapes the index directory: {stored_path}") from exc
    if not candidate.is_file():
        raise ValueError(f"HTML snapshot not found: {candidate}")
    return candidate


def copy_resources(skill_dir: Path, index_path: Path, pages: list[dict[str, Any]]) -> None:
    references_dir = skill_dir / "references"
    html_dir = references_dir / "html"
    scripts_dir = skill_dir / "scripts"
    html_dir.mkdir(parents=True, exist_ok=True)
    scripts_dir.mkdir(parents=True, exist_ok=True)

    compact_pages: list[dict[str, Any]] = []
    used_names: set[str] = set()
    for page in pages:
        source = resolve_html_path(index_path, str(page["html_path"]))
        name = source.name
        if name in used_names:
            name = f"{source.stem}-{len(used_names) + 1}{source.suffix}"
        used_names.add(name)
        destination = html_dir / name
        shutil.copyfile(source, destination)
        compact_pages.append(
            {
                "url": page["url"],
                "title": page["title"],
                "description": page["description"],
                "keywords": page["keywords"],
                "html_path": f"references/html/{name}",
            }
        )
    (references_dir / "web-index.jsonl").write_text(
        "\n".join(json.dumps(page, ensure_ascii=False, separators=(",", ":")) for page in compact_pages) + "\n",
        encoding="utf-8",
    )

    for filename in ("search_index.py", "fetch_rendered_html.py"):
        source = Path(__file__).with_name(filename)
        if not source.is_file():
            raise ValueError(f"required helper script not found: {source}")
        shutil.copyfile(source, scripts_dir / filename)


def zip_directory(source_dir: Path, zip_path: Path) -> None:
    zip_path.parent.mkdir(parents=True, exist_ok=True)
    temporary_zip = zip_path.with_suffix(zip_path.suffix + ".tmp")
    if temporary_zip.exists():
        temporary_zip.unlink()
    try:
        with zipfile.ZipFile(temporary_zip, "w", compression=zipfile.ZIP_DEFLATED) as archive:
            for path in sorted(source_dir.rglob("*")):
                if path.is_file():
                    archive.write(path, path.relative_to(source_dir.parent).as_posix())
        temporary_zip.replace(zip_path)
    finally:
        if temporary_zip.exists():
            temporary_zip.unlink()


def build(args: argparse.Namespace) -> Path:
    index_path = Path(args.index).resolve()
    metadata_path = Path(args.metadata).resolve()
    zip_path = Path(args.zip_out).resolve()
    pages = load_index(index_path)
    metadata = load_metadata(metadata_path, {str(page["url"]) for page in pages})
    coverage = load_crawl_coverage(index_path.parent / "crawl.log", len(pages))
    if zip_path.suffix.lower() != ".zip":
        raise ValueError("--zip-out must end with .zip")

    with tempfile.TemporaryDirectory(prefix="web-to-skill-") as temporary_root:
        skill_dir = Path(temporary_root) / metadata["name"]
        (skill_dir / "agents").mkdir(parents=True, exist_ok=True)
        (skill_dir / "SKILL.md").write_text(build_skill_markdown(metadata, coverage), encoding="utf-8")
        (skill_dir / "agents" / "openai.yaml").write_text(build_openai_yaml(metadata), encoding="utf-8")
        copy_resources(skill_dir, index_path, pages)
        zip_directory(skill_dir, zip_path)
    return zip_path


def main() -> int:
    args = parse_args()
    try:
        zip_path = build(args)
    except (OSError, ValueError) as exc:
        print(str(exc), file=sys.stderr)
        return 1
    print(zip_path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
